const path = require('path');
const Koa = require('koa');
const koaWebpack = require('koa-webpack');
const webpackConfig = require('./webpack.config');

async function start() {
    const app = new Koa();

    // Use koa-webpack middleware to support HMR.
    const koaWebpackMiddleware = await koaWebpack({ config: webpackConfig });
    app.use(koaWebpackMiddleware);

    // Serve HTML from memory, generated by HTML Webpack Plugin.
    app.use(async (ctx) => {
        const filename = path.resolve(webpackConfig.output.path, 'index.html');
        ctx.response.type = 'html';
        ctx.response.body = koaWebpackMiddleware.devMiddleware.fileSystem.createReadStream(filename);
    });

    app.listen(3000);
}

start();
