const path = require('path');
const fs = require('fs');
const Koa = require('koa');
const koaWebpack = require('koa-webpack');
const serve = require('koa-static');
const { ApolloServer } = require('apollo-server-koa');
const webpackDevConfig = require('../../webpack.dev');
const webpackProdConfig = require('../../webpack.prod');
const resolvers = require('./api');

const PORT = process.env.PORT || 3000;

async function start() {
  const app = new Koa();

  // Register API middleware
  const typeDefs = fs.readFileSync(path.resolve(__dirname, 'schema.graphql'), 'utf8');
  const server = new ApolloServer({ typeDefs, resolvers });
  server.applyMiddleware({ app });

  // Serve client
  if (process.env.NODE_ENV !== 'production') {
    // Use middleware to support HMR.
    const devMiddleware = await koaWebpack({ config: webpackDevConfig });
    app.use(devMiddleware);

    // Serve HTML from memory, generated by HTML Webpack Plugin
    app.use(async ctx => {
      const filename = path.resolve(webpackDevConfig.output.path, 'index.html');
      const devFs = devMiddleware.devMiddleware.fileSystem;
      ctx.response.type = 'html';
      ctx.response.body = devFs.createReadStream(filename);
    });
  } else {
    // Serve static build
    console.log('Running in production mode');
    const staticPath = webpackProdConfig.output.path;
    app.use(serve(path.resolve(staticPath)));
  }

  app.listen(PORT);
  console.info(`🚀 Server listening on port ${PORT}`);
}

start();
