const path = require('path');
const Koa = require('koa');
const koaWebpack = require('koa-webpack');
const serve = require('koa-static');
const Router = require('koa-router');
const webpackDevConfig = require('../../webpack.dev');
const webpackProdConfig = require('../../webpack.prod');

const PORT = process.env.PORT || 3000;

async function start() {
  const app = new Koa();
  const router = new Router();

  if (process.env.NODE_ENV !== 'production') {
    // Use middleware to support HMR.
    const devMiddleware = await koaWebpack({ config: webpackDevConfig });
    app.use(devMiddleware);

    // Serve HTML from memory, generated by HTML Webpack Plugin.
    app.use(async ctx => {
      const filename = path.resolve(webpackDevConfig.output.path, 'index.html');
      const fs = devMiddleware.devMiddleware.fileSystem;
      ctx.response.type = 'html';
      ctx.response.body = fs.createReadStream(filename);
    });
  } else {
    // Serve static build.
    console.log('Running in production mode');
    const staticPath = webpackProdConfig.output.path;
    app.use(serve(path.resolve(staticPath)));
  }

  app.listen(PORT);
  console.log(`Server listening on port ${PORT}`);
}

start();
